# Generated by Django 5.1.4 on 2025-11-11 04:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(db_index=True, max_length=100)),
                ("issue_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("supplier_name", models.CharField(max_length=255)),
                (
                    "supplier_tax_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("supplier_address", models.TextField(blank=True, null=True)),
                ("buyer_name", models.CharField(max_length=255)),
                (
                    "buyer_tax_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("buyer_address", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(blank=True, help_text="Raw OCR text", null=True),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="invoices/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "tiff",
                                    "tif",
                                ]
                            ),
                            django.core.validators.MaxValueValidator(26214400),
                        ],
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("olmocr", "OlmOCR"),
                            ("marker_deepseek_r1", "Marker + DeepSeek R1"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw OCR provider response"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("tax_id", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=10
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
                "db_table": "invoice_line_items",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="billing.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "issue_date"],
                name="invoices_organiz_612bc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["number", "organization"], name="invoices_number_7c984b_idx"
            ),
        ),
    ]
